// page list array
var pageList = [
  {
    menuNm: "메뉴명1",
    menuCode: "MENU_CD001",
    pageNm: "페이지명_1",
    fileFolder: "temp",
    fileName: "temp.html",
    author: "",
    isComplete: 2,
    completeDate: "2024-01-09",
    dueToDate: "2024-01-11",
    priority: 3,
    // pageType: , // 페이지 형식 고민 후 재정의
    modifyInfo: {
      requestDate: "2024-01-15",
      completeDate: "",
      requestContent: "수정요청 사항입니다",
      requestStatus: 0,
    },
    functionSpec: [
      "기능을 나열합니다",
      "기능을 나열합니다",
      "기능을 나열합니다",
    ],
    comments:
      "*줄바꿈 되나요* first|줄바꿈 *되나요* second|*줄바꿈* 되나요 *third*",
  },
  {
    menuNm: "메뉴명1",
    menuCode: "MENU_CD001",
    pageNm: "페이지명_2",
    fileFolder: "temp",
    fileName: "temp.html",
    author: "",
    isComplete: 1,
    completeDate: "",
    dueToDate: "2024-01-10",
    priority: 2,
    // pageType: ,
    modifyInfo: {
      requestDate: "2024-01-15",
      completeDate: "",
      requestContent: "수정요청 사항입니다",
      requestStatus: 1,
    },
    functionSpec: [],
    comments: "",
  },
  {
    menuNm: "메뉴명1",
    menuCode: "MENU_CD001",
    pageNm: "페이지명_3",
    fileFolder: "temp",
    fileName: "temp.html",
    author: "",
    isComplete: 2,
    completeDate: "2024-01-10",
    dueToDate: "2024-01-10",
    priority: 1,
    // pageType: ,
    modifyInfo: {
      requestDate: "2024-01-15",
      completeDate: "",
      requestContent: "수정요청 사항입니다",
      requestStatus: 2,
    },
    functionSpec: [
      "기능을 나열합니다",
      "기능을 나열합니다",
      "기능을 나열합니다",
    ],
    comments: "",
  },
  {
    menuNm: "메뉴명2",
    menuCode: "MENU_CD002",
    pageNm: "페이지명_2_2",
    fileFolder: "temp",
    fileName: "temp.html",
    author: "",
    isComplete: 1,
    completeDate: "",
    dueToDate: "2024-01-16",
    priority: 4,
    // pageType: ,
    modifyInfo: {
      requestDate: "",
      completeDate: "",
      requestContent: "",
      requestStatus: 2,
    },
    functionSpec: [
      "기능을 나열합니다",
      "기능을 나열합니다",
      "기능을 나열합니다",
    ],
    comments: "",
  },
  {
    menuNm: "메뉴명2",
    menuCode: "MENU_CD002",
    pageNm: "페이지명_3",
    fileFolder: "temp",
    fileName: "temp.html",
    author: "",
    isComplete: 0,
    completeDate: "",
    dueToDate: "2024-01-13",
    priority: 5,
    // pageType: ,
    modifyInfo: {
      requestDate: "",
      completeDate: "",
      requestContent: "",
      requestStatus: 2,
    },
    functionSpec: [
      "기능을 나열합니다",
      "기능을 나열합니다",
      "기능을 나열합니다",
    ],
    comments: "",
  },
];
