var pageList = {
  columns: [
    {
      key: "menuNm",
      label: "메뉴명",
    },
    {
      key: "pageNm",
      label: "페이지명",
    },
    {
      key: "fileName",
      label: "페이지 url",
    },
    // {
    //   key: "author",
    //   label: "담당자",
    // },
    {
      key: "priority",
      label: "우선순위",
    },
    {
      key: "functionSpec",
      label: "기능명세",
    },
    // {
    //   key: "riskStatus",
    //   label: "위험도",
    // },
    // {
    //   key: "isComplete",
    //   label: "진행상태",
    // },
    // {
    //   key: "dueToDate",
    //   label: "완료예정일",
    // },
    // {
    //   key: "completeDate",
    //   label: "완료일",
    // },
    {
      key: "comments",
      label: "비고",
    },
    // {
    //   key: "modifyInfo",
    //   label: "수정사항",
    //   child: [
    //     {
    //       key: "requestDate",
    //       label: "요청일",
    //     },
    //     {
    //       key: "completeDate",
    //       label: "완료일",
    //     },
    //     {
    //       key: "requestContent",
    //       label: "내용",
    //     },
    //     {
    //       key: "requestStatus",
    //       label: "진행상태",
    //     },
    //   ],
    // },
  ],
  rows: [
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Accordion",
      fileFolder: "components/accordion",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Alerts",
      fileFolder: "components/alert",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Buttons",
      fileFolder: "components/buttons",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "ButtonGroup",
      fileFolder: "components/buttonGroup",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "CallOut",
      fileFolder: "components/callout",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Badge",
      fileFolder: "components/badge",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Avatar",
      fileFolder: "components/avatar",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Chip",
      fileFolder: "components/chip",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
    {
      menuNm: "Components",
      menuCode: "MENU_CD001",
      pageNm: "Toast",
      fileFolder: "components/toast",
      fileName: "index.html",
      author: "",
      isComplete: 2,
      completeDate: "2024-01-23",
      dueToDate: "2024-01-11",
      priority: 3,
      // pageType: , // 페이지 형식 고민 후 재정의
      modifyInfo: {
        requestDate: "2024-01-15",
        completeDate: "",
        requestContent: "수정요청 사항입니다",
        requestStatus: 0,
      },
      functionSpec: [],
      comments: "",
    },
  ],
};
