var utilsInfo = {
  projectTitle: "Project명",
  filterSelect: [
    {
      value: "all",
      label: "전체메뉴",
    },
    {
      value: "MENU_CD001",
      label: "메뉴명1",
    },
    {
      value: "MENU_CD002",
      label: "메뉴명2",
    },
  ],
  filterRisk: [
    {
      value: "on-track",
      label: "정상",
      labelClassName: "on-track",
      riskId: "filterDueTo01",
      statusClassname: "checkbox status-check",
      isChecked: true,
    },
    {
      value: "at-risk",
      label: "완료일 임박",
      labelClassName: "at-risk",
      riskId: "filterDueTo02",
      statusClassname: "checkbox status-check",
      isChecked: true,
    },
    {
      value: "high-risk",
      label: "지연",
      labelClassName: "high-risk",
      riskId: "filterDueTo03",
      statusClassname: "checkbox status-check",
      isChecked: true,
    },
  ],
  filterProgress: [
    {
      value: "0",
      label: "진행 대기",
      labelClassName: "",
      riskId: "filterDueTo01",
      statusClassname: "checkbox progress-check",
      isChecked: true,
    },
    {
      value: "1",
      label: "진행중",
      labelClassName: "",
      riskId: "filterDueTo02",
      statusClassname: "checkbox progress-check",
      isChecked: true,
    },
    {
      value: "2",
      label: "완료",
      labelClassName: "",
      riskId: "filterDueTo03",
      statusClassname: "checkbox progress-check",
      isChecked: true,
    },
  ],
  statusList: [],
  pageListData: {
    columns: [
      {
        key: "menuNm",
        label: "메뉴명",
        isLink: false,
      },
      {
        key: "pageNm",
        label: "페이지명",
        isLink: false,
      },
      {
        key: "fileName",
        label: "페이지 url",
        isLink: false,
      },
      {
        key: "author",
        label: "담당자",
        isLink: false,
      },
      {
        key: "priority",
        label: "우선순위",
        isLink: false,
      },
      {
        key: "functionSpec",
        label: "기능명세",
        isLink: false,
      },
      {
        key: "riskStatus",
        label: "위험도",
        isLink: false,
      },
      {
        key: "isComplete",
        label: "진행상태",
        isLink: false,
      },
      {
        key: "dueToDate",
        label: "완료예정일",
        isLink: false,
      },
      {
        key: "completeDate",
        label: "완료일",
        isLink: false,
      },
      {
        key: "comments",
        label: "비고",
        isLink: false,
      },
    ],
    rows: [
      {
        menuNm: "메뉴명1",
        menuCode: "MENU_CD001",
        pageNm: "페이지명_1",
        fileFolder: "temp",
        fileName: "temp.html",
        author: "",
        isComplete: 2,
        completeDate: "2024-01-09",
        dueToDate: "2024-01-11",
        priority: 3,
        // pageType: , // 페이지 형식 고민 후 재정의
        modifyInfo: {
          requestDate: "2024-01-15",
          completeDate: "",
          requestContent: "수정요청 사항입니다",
          requestStatus: 0,
        },
        functionSpec: [
          "~기능을 나열합니다~",
          "기능을 *나열*합니다",
          "기능을 나열합니다",
        ],
        comments:
          "*줄바꿈 되나요* first|줄바꿈 *~되나요~* second|*줄바꿈* 되나요 *third*",
      },
      {
        menuNm: "메뉴명1",
        menuCode: "MENU_CD001",
        pageNm: "페이지명_2",
        fileFolder: "temp",
        fileName: "temp.html",
        author: "",
        isComplete: 1,
        completeDate: "",
        dueToDate: "2024-01-10",
        priority: 2,
        // pageType: ,
        modifyInfo: {
          requestDate: "2024-01-15",
          completeDate: "",
          requestContent: "수정요청 사항입니다",
          requestStatus: 1,
        },
        functionSpec: [],
        comments: "",
      },
      {
        menuNm: "메뉴명1",
        menuCode: "MENU_CD001",
        pageNm: "페이지명_3",
        fileFolder: "temp",
        fileName: "temp.html",
        author: "",
        isComplete: 2,
        completeDate: "2024-01-10",
        dueToDate: "2024-01-10",
        priority: 1,
        // pageType: ,
        modifyInfo: {
          requestDate: "2024-01-15",
          completeDate: "",
          requestContent: "수정요청 사항입니다",
          requestStatus: 2,
        },
        functionSpec: [
          "기능을 나열합니다",
          "기능을 나열합니다",
          "기능을 나열합니다",
        ],
        comments: "",
      },
      {
        menuNm: "메뉴명2",
        menuCode: "MENU_CD002",
        pageNm: "페이지명_2_2",
        fileFolder: "temp",
        fileName: "temp.html",
        author: "",
        isComplete: 1,
        completeDate: "",
        dueToDate: "2024-01-16",
        priority: 4,
        // pageType: ,
        modifyInfo: {
          requestDate: "",
          completeDate: "",
          requestContent: "",
          requestStatus: 2,
        },
        functionSpec: [
          "기능을 나열합니다",
          "기능을 나열합니다",
          "기능을 나열합니다",
        ],
        comments: "",
      },
      {
        menuNm: "메뉴명2",
        menuCode: "MENU_CD002",
        pageNm: "페이지명_3",
        fileFolder: "temp",
        fileName: "temp.html",
        author: "",
        isComplete: 0,
        completeDate: "",
        dueToDate: "2024-01-13",
        priority: 5,
        // pageType: ,
        modifyInfo: {
          requestDate: "",
          completeDate: "",
          requestContent: "",
          requestStatus: 2,
        },
        functionSpec: [
          "기능을 나열합니다",
          "기능을 나열합니다",
          "기능을 나열합니다",
        ],
        comments: "",
      },
    ],
  },
};
