[
  {
    menuNm: "물품청구",
    pageNm: "메뉴 그룹",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "물품 청구 절차 안내 가이드",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "물품 청구 내역 조회",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "단건 물품 청구",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "Department 검색 레이어",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "Project 검색 레이어",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "계정 검색 레이어",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "Plant 검색 레이어",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "품목 검색 레이어",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "단건 물품 청구(예산부족)",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "단건 물품 청구 성공",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "단건 물품 청구 실패",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
  {
    menuNm: "물품청구",
    pageNm: "다건 물품/불량 청구 메시지",
    pageUrl: "",
    author: "",
    isComplete: false,
    comments: "",
  },
];
